# Generated by Django 5.2.1 on 2025-05-26 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=70)),
                ('discount', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('date_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=70)),
                ('appellation', models.CharField(max_length=255)),
                ('cost', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('os_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prog_names', models.CharField(max_length=255)),
                ('prog_version', models.CharField(max_length=255)),
                ('instal_date', models.DateField()),
                ('update_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=70)),
                ('discount', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('date_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=70)),
                ('pc_range', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField()),
                ('order_price', models.PositiveIntegerField()),
                ('fk_order_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('fk_order_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateField()),
                ('time_end', models.DateField()),
                ('cost', models.PositiveIntegerField()),
                ('fk_session_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('fk_session_pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pc')),
                ('fk_session_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('price', models.PositiveIntegerField()),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pc')),
                ('techician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.technician')),
            ],
        ),
        migrations.CreateModel(
            name='MenuOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.menu')),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order')),
            ],
            options={
                'unique_together': {('menu', 'orders')},
            },
        ),
        migrations.CreateModel(
            name='PCSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pc')),
                ('software_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.softwarekit')),
            ],
            options={
                'unique_together': {('pc', 'software_kit')},
            },
        ),
        migrations.CreateModel(
            name='PCTechnician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pc')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.technician')),
            ],
            options={
                'unique_together': {('pc', 'technician')},
            },
        ),
    ]
