# Generated by Django 5.2.1 on 2025-05-26 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='discount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Мінімальна знижка — 1'), django.core.validators.MaxValueValidator(100, message='Максимальна знижка — 100')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='cost',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10, message='Мінімальна вартість — 10'), django.core.validators.MaxValueValidator(100000, message='Максимальна вартість — 100000')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10, message='Мінімальна вартість — 10'), django.core.validators.MaxValueValidator(100000, message='Максимальна вартість — 100000')]),
        ),
        migrations.AlterField(
            model_name='repair',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10, message='Мінімальна вартість — 10'), django.core.validators.MaxValueValidator(100000, message='Максимальна вартість — 100000')]),
        ),
        migrations.AlterField(
            model_name='session',
            name='cost',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10, message='Мінімальна вартість — 10'), django.core.validators.MaxValueValidator(10000, message='Максимальна вартість — 10000')]),
        ),
    ]
