# Generated by Django 5.2.1 on 2025-05-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_client_discount_alter_menu_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
