# Generated by Django 5.2.1 on 2025-05-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_client_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
