# Generated by Django 5.2.1 on 2025-05-26 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_client_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, message='Мінімальна знижка — 1'), django.core.validators.MaxValueValidator(100, message='Максимальна знижка — 100')]),
        ),
    ]
